inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
  Exclude:
    - 'test/*.rb'
  SuggestExtensions: false
  TargetRubyVersion: '2.7'
# ~~~ Layout ~~~
Layout/HashAlignment:
  Include:
    - 'lib/**/*.rb'
Layout/LineLength:
  Include:
    - 'lib/**/*.rb'
# ~~~ Lint ~~~
# ~~~ Metrics ~~~
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Exclude:
    - 'bin/*'
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 10
# ~~~ Naming ~~~
Naming/InclusiveLanguage:
  Enabled: false
Naming/VariableNumber:
  Enabled: false # too much false positive
# ~~~ Style ~~~
Style/AccessorGrouping:
  Enabled: false # for yard
Style/BisectedAttrAccessor:
  Enabled: false # for yard
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantReturn:
  Enabled: false

